spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpashop?serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  security:
    user:
      name: admin
      password : 1234
      Role : admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${LOCAL_MAIL_USERNAME}
    password: ${LOCAL_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true