spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:jpashop
    driverClassName: org.h2.Driver
    username: sa
    password:
    sql:
      init:
        mode: always
  h2:
    console:
      enabled: true
  security:
    user:
      name: admin
      password: 1234
      roles: admin