spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/jpashop?characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show_sql : true
  security:
    user:
      name: admin
      password: 1234
      roles: admin