INSERT INTO CATEGORY (ID,NAME) VALUES (0,'Music');
INSERT INTO CATEGORY (ID,NAME) VALUES (1,'Artwork');
INSERT INTO CATEGORY (ID,NAME) VALUES (2,'Movie');
INSERT INTO CATEGORY (ID,NAME) VALUES (3,'Ebook');
INSERT INTO CATEGORY (ID,NAME) VALUES (4,'Course');